---
name: Quality Assurance
on:
    push: ~
    pull_request: ~

jobs:
    build:
        name: '[Build/test] Python ${{ matrix.python }}'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: [ '3.13' ]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python }}
            - run: python -m pip install --upgrade pipenv wheel
            - run: pipenv install
            - run: pipenv run "pytest"